name: Docker image update check
on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v2
        with:
          base-image: alpine:latest
          image: mogzol/nordvpn-tinyproxy:latest

  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit
    needs: check
    if: needs.check.outputs.needs-updating == 'true'
